### ISSUE TITLE
0.2.3 on crates.io is missing opus sources

### ISSUE THREAD

**Issue by alyssais** [DoumanAsh/opusic-sys#3]

**Comment by DoumanAsh** [comment]
yeah, sadly docs.rs prohibit to use network nowadays.
So while it is retarded, we're going to bandle source code together now.

If possible take test if this PR with cmake works just fine as 0.2.3 https://github.com/DoumanAsh/opusic-sys/pull/2

**Comment by DoumanAsh** [comment]
Just a note `0.2.3` has almost zero difference from `0.2.2`
There was added one enum variant only.

And now that we released `0.3` with sources bundled together there should be no longer any problem with docs.rs https://docs.rs/opusic-sys/0.3.0/opusic_sys/
