### ISSUE TITLE
docs.rs can't build opusic-sys

### ISSUE THREAD

**Issue by DuckerMan** [DoumanAsh/opusic-sys#4]
Hi there! docs.rs can't build documentation for this crate.
https://docs.rs/crate/magnum-opus/0.3.0/builds/254213

I think, you should add "docs-only" feature, then add that feature in `Cargo.toml`. [There](https://doc.rust-lang.org/cargo/reference/manifest.html#the-metadata-table)'s guide.

**Comment by DoumanAsh** [comment]
@DuckerMan try `0.3` please. 
It uses CMake and no longer requires network access

**Comment by DuckerMan** [comment]
https://docs.rs/crate/magnum-opus/0.3.1/builds/257807

Nah.

**Comment by DoumanAsh** [comment]
@DuckerMan This is `0.2.3` rather than `0.3.0` 😄 
As you can see [0.3.0](https://docs.rs/crate/opusic-sys/0.3.0) successfully builds

**Comment by DoumanAsh** [comment]
I see now you have https://docs.rs/magnum-opus/0.3.2/magnum_opus/
So hopefully you're good

**Comment by DuckerMan** [comment]
Yep, forgot to close, thank you
